# ??? SERVER ??????????????????????????????????????????
server.port=8080

# ??? APP INFO ????????????????????????????????????????
spring.application.name=portfolio

# ??? DEVTOOLS ????????????????????????????????????????
spring.devtools.restart.enabled=true

# ??? LOGGING ?????????????????????????????????????????
logging.level.com.salasnorman.portfolio=DEBUG
logging.level.org.springframework.web=INFO